services:
  - type: web
    name: nextjs-app
    runtime: node # Add the runtime property
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: web
        src: '/'
        dest: '/'
    publish:
      directory: dist
