services:
  - type: web
    name: nextjs-static
    runtime: static
    buildCommand: yarn install && yarn build && yarn export
    staticPublishPath: out
    pullRequestPreviewsEnabled: true 
    envVars:
      - key: NODE_ENV
        value: production
